# Generated by Django 5.0.4 on 2024-05-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shipping',
            new_name='shippingPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='taxPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='totalPrice',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='notes',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
