# Generated by Django 5.0.4 on 2024-05-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
