# Generated by Django 5.0.4 on 2024-05-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_orderitem_image_alter_orderitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
